# Generated by Django 4.0.5 on 2022-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_post_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
