# Generated by Django 4.0.5 on 2022-06-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood'),
        ),
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.neighborhood'),
        ),
    ]
