# Generated by Django 4.0.5 on 2022-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_post_hood_alter_business_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='occupants',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
