# Generated by Django 4.0.5 on 2022-06-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0006_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='name',
            new_name='hood_name',
        ),
    ]
